language: php

php:
  - 5.4
  - 5.5

env:
  global:
    - CODER_REPO='git://drupalcode.org/project/coder.git'
    - CODER_VERSION='7.x-2.2'

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  fast_finish: true

install:

  # Update composer
  - composer selfupdate

  # Install global composer requires.
  - composer global require --prefer-dist --no-interaction drush/drush:6.*
  - composer global require --prefer-dist --no-interaction phing/phing:2.7.*
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Prepare build and install composer dependencies
  - cp build.travis.properties build.properties
  - phing prepare
  - phing behat:init

  # Build the codebase.
  - phing make

  # Verify that all the .make files will work on Drupal.org.
  - phing verify-make

  # Disable sendmail.
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:

  # Install the site.
  - phing site-install

  # Start the server.
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - SERVER_PID=$!
  - sleep 3

script:

  - phing phpcs
  - phing behat

after_script:

  # Stop the webserver so that it's not still running when MySQL is stopped.
  - kill $SERVER_PID

notifications:
  email:
    recipients:
      - agov-devs@previousnext.com.au
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#agov"
    on_success: always
    on_failure: always
