language: php

php:
- 5.3
- 5.5

cache:
  bundler: true
  apt: true

env:
- COMPOSER_BIN_DIR=bin

notifications:
  email:
  - adam.malone@acquia.com
  - paul.killer@gmail.com
  slack:
    secure: jflE/Zs73rGpsnhN7qXqYDaVKyuwlNyQByMZrcwq2Cj7O84N3yp5x7fDbDTsJ4qYExBj3cnUXGzuS/SEtDWVdpwpjS4rcfL1uQvU4ZCuI6U9mI/KTWVGgD5+DkdS8/jZxsIfDtM8OYBwukqyaUCgGRzV609HR0NPiUofKnMxAPo=

before_install:
- sudo apt-get update > /dev/null
- composer selfupdate

install:
- composer install --prefer-source
- export PATH=$PATH:$TRAVIS_BUILD_DIR/bin

before_script:
# Install Apache
- sudo apt-get install -y apache2 libapache2-mod-fastcgi
- sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv
  version-name)/etc/php-fpm.conf
- sudo a2enmod rewrite actions fastcgi alias
- echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
- sudo cp -f tests/travis/travis-ci-apache /etc/apache2/sites-available/default
- sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
- sudo service apache2 restart
# Create Database
- mysql -e 'CREATE DATABASE travis_ci_govcms_drupal;'
# Build the codebase
- phing -f build.xml build

script:
# Run the install
- phing -f build.xml install
