language: php

php:
  - 5.4
  - 5.5

env:
  global:
    - CODER_REPO='git://drupalcode.org/project/coder.git'
    - CODER_VERSION='7.x-2.2'

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  fast_finish: true

install:

  # Install composer dependencies
  - composer selfupdate
  - composer install

  # Install global composer requires.
  - composer global require --prefer-source --no-interaction drush/drush:6.*
  - composer global require --prefer-source --no-interaction phing/phing:2.7.*
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Download make file validator.
  - drush dl -y drupalorg_drush-7.x-1.x-dev --destination=$HOME/.drush
  - drush cc drush

  # Build Codebase
  - cp build.travis.properties build.properties
  - phing make

  # Verify that all the .make files will work on Drupal.org.
  - phing verify-make

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Create a database for our Drupal site.
  - "mysql -e 'create database drupal;'"

before_script:

  - phing site-install
  - phing file-dirs

  # Start the server
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - SERVER_PID=$!
  - sleep 3

script:

  - phing phpcs

after_script:

  # Stop the webserver so that it's not still running when MySQL is stopped.
  - kill $SERVER_PID

notifications:
  email:
    recipients:
      - agov-devs@previousnext.com.au
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#agov"
    on_success: always
    on_failure: always
