default:
  &app_url: 'http://127.0.0.1:8888'
  &app_dir: drupal
  extensions:
    Behat\MinkExtension\Extension:
      base_url: *app_url
    Drupal\DrupalExtension\Extension:
      drush:
        root: *app_dir
      drupal:
        drupal_root: *app_dir

drupal7:
  extensions:
    Drupal\DrupalExtension\Extension:
      drupal:
        drupal_root: *app_dir
      drush:
        root: *app_dir
